import puppeteer from 'puppeteer';

export const generatePdfReport = async (data) => {
  const { stats, projectMetadata, criticalIssues } = data;

  const htmlContent = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; line-height: 1.6; padding: 40px; }
        h1 { color: #1e293b; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; margin-bottom: 20px; }
        h2 { color: #334155; margin-top: 30px; }
        .stats-grid { display: flex; flex-wrap: wrap; gap: 20px; margin-bottom: 30px; }
        .stat-box { background: #f8fafc; border: 1px solid #e2e8f0; padding: 15px; border-radius: 8px; flex: 1; min-width: 150px; text-align: center; }
        .stat-value { font-size: 24px; font-weight: bold; color: #0f172a; }
        .stat-label { font-size: 12px; color: #64748b; text-transform: uppercase; }
        table { w-full border-collapse: collapse; margin-top: 20px; width: 100%; }
        th, td { border: 1px solid #e2e8f0; padding: 10px; text-align: left; font-size: 12px; }
        th { background: #f1f5f9; font-weight: bold; }
        .critical { color: #dc2626; font-weight: bold; }
        .high { color: #d97706; font-weight: bold; }
      </style>
    </head>
    <body>
      <h1>SEO Migration Audit Report</h1>
      <p><strong>Project:</strong> ${projectMetadata?.name || 'Untitled Project'}</p>
      <p><strong>Generated on:</strong> ${new Date().toLocaleDateString()}</p>
      
      <h2>Migration Summary</h2>
      <div class="stats-grid">
        <div class="stat-box">
          <div class="stat-value">${stats?.totalUrls || 0}</div>
          <div class="stat-label">Total URLs</div>
        </div>
        <div class="stat-box">
          <div class="stat-value">${stats?.mappedUrls || 0}</div>
          <div class="stat-label">Mapped</div>
        </div>
        <div class="stat-box">
          <div class="stat-value">${stats?.unmappedUrls || 0}</div>
          <div class="stat-label">Unmapped</div>
        </div>
        <div class="stat-box">
          <div class="stat-value">${stats?.criticalIssuesCount || 0}</div>
          <div class="stat-label">Critical Parity Issues</div>
        </div>
      </div>

      <h2>Pre vs. Post SEO Parity Issues</h2>
      ${criticalIssues && criticalIssues.length > 0 ? `
        <table>
          <thead>
            <tr>
              <th>Severity</th>
              <th>Issue Type</th>
              <th>Source URL</th>
              <th>Source Value</th>
              <th>Target URL</th>
              <th>Target Value</th>
            </tr>
          </thead>
          <tbody>
            ${criticalIssues.map(issue => `
              <tr>
                <td class="${issue.severity.toLowerCase()}">${issue.severity}</td>
                <td>${issue.title}</td>
                <td>${issue.sourceUrl}</td>
                <td>${issue.sourceValue || 'N/A'}</td>
                <td>${issue.targetUrl || 'Unmapped'}</td>
                <td>${issue.targetValue || 'N/A'}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      ` : '<p>No critical SEO parity issues found. Excellent work!</p>'}
      
      <div style="margin-top: 50px; font-size: 10px; color: #94a3b8; text-align: center;">
        Generated by Antigravity Website Migration Tool
      </div>
    </body>
    </html>
  `;

  const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] });
  const page = await browser.newPage();
  await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
  const pdfBuffer = await page.pdf({ format: 'A4', printBackground: true, margin: { top: '20px', bottom: '20px' } });
  await browser.close();

  return pdfBuffer;
};
