import Papa from 'papaparse';
import * as XLSX from 'xlsx';
import { UrlMapping, SynthesizedPattern, ExportFormat, MigrationSummaryStats, ProjectMetadata } from '../types/migration';
import { MIGRATION_CHECKLISTS } from '../data/checklists';

/**
 * Automatically synthesizes regex rules by finding common directory prefix shifts
 */
export function synthesizeRegexPatterns(mappings: UrlMapping[]): SynthesizedPattern[] {
  const patterns: SynthesizedPattern[] = [];
  const prefixShiftCounts = new Map<string, { targetPrefix: string; count: number; samples: [string, string][] }>();

  for (const m of mappings) {
    if (!m.target || m.confidenceScore < 80) continue;

    const srcPath = m.source.normalizedPath;
    const tgtPath = m.target.normalizedPath;

    // Detect /blog/2023/xx -> /insights/xx or /blog/xx -> /articles/xx
    const srcSegments = srcPath.split('/').filter(Boolean);
    const tgtSegments = tgtPath.split('/').filter(Boolean);

    if (srcSegments.length >= 2 && tgtSegments.length >= 1) {
      const srcPrefix = '/' + srcSegments[0];
      const tgtPrefix = '/' + tgtSegments[0];

      if (srcPrefix !== tgtPrefix) {
        const key = `${srcPrefix}=>${tgtPrefix}`;
        if (!prefixShiftCounts.has(key)) {
          prefixShiftCounts.set(key, { targetPrefix: tgtPrefix, count: 0, samples: [] });
        }
        const data = prefixShiftCounts.get(key)!;
        data.count++;
        if (data.samples.length < 3) {
          data.samples.push([srcPath, tgtPath]);
        }
      }
    }

    // Detect Date Strip: /blog/2022/04/my-post -> /blog/my-post
    const dateMatch = srcPath.match(/^\/([^/]+)\/\d{4}\/\d{2}\/(.+)$/);
    if (dateMatch) {
      const parent = dateMatch[1];
      const slug = dateMatch[2];
      if (tgtPath === `/${parent}/${slug}` || tgtPath === `/articles/${slug}` || tgtPath === `/blog/${slug}`) {
        const key = `date_strip_${parent}`;
        if (!prefixShiftCounts.has(key)) {
          prefixShiftCounts.set(key, { targetPrefix: `/${parent}/$1`, count: 0, samples: [] });
        }
        const data = prefixShiftCounts.get(key)!;
        data.count++;
        if (data.samples.length < 3) {
          data.samples.push([srcPath, tgtPath]);
        }
      }
    }
  }

  let index = 0;
  for (const [key, data] of prefixShiftCounts.entries()) {
    if (data.count >= 2) {
      if (key.startsWith('date_strip_')) {
        const parent = key.replace('date_strip_', '');
        patterns.push({
          id: `pat_${index++}`,
          name: `Strip Date Hierarchy from /${parent}/`,
          sourcePattern: `^/${parent}/\\d{4}/\\d{2}/(.*)$`,
          targetPattern: `/${parent}/$1`,
          affectedCount: data.count,
          sampleSource: data.samples[0]?.[0] || `/${parent}/2023/05/example`,
          sampleTarget: data.samples[0]?.[1] || `/${parent}/example`,
          isActive: true,
          type: 'DATE_STRIP'
        });
      } else {
        const [srcP, tgtP] = key.split('=>');
        patterns.push({
          id: `pat_${index++}`,
          name: `Directory Shift: ${srcP}/ $\\rightarrow$ ${tgtP}/`,
          sourcePattern: `^${srcP}/(.*)$`,
          targetPattern: `${tgtP}/$1`,
          affectedCount: data.count,
          sampleSource: data.samples[0]?.[0] || `${srcP}/item`,
          sampleTarget: data.samples[0]?.[1] || `${tgtP}/item`,
          isActive: true,
          type: 'DIRECTORY_SHIFT'
        });
      }
    }
  }

  return patterns;
}

/**
 * Generates an XML Sitemap for the new target website
 */
export function generateXmlSitemap(targetEntries: { url: string, statusCode?: number }[]): string {
  const validUrls = targetEntries
    .filter(e => e.statusCode === 200 || !e.statusCode)
    .map(e => e.url.split('#')[0]) // remove hash
    .filter((url, index, self) => self.indexOf(url) === index); // deduplicate

  const lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
  ];

  for (const url of validUrls) {
    // Basic XML escaping
    const escapedUrl = url.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');
    lines.push(`  <url>`);
    lines.push(`    <loc>${escapedUrl}</loc>`);
    lines.push(`    <changefreq>weekly</changefreq>`);
    lines.push(`    <priority>0.8</priority>`);
    lines.push(`  </url>`);
  }

  lines.push('</urlset>');
  return lines.join('\n');
}

/**
 * Generates Apache .htaccess 301 configuration
 */
export function generateHtaccess(mappings: UrlMapping[], patterns: SynthesizedPattern[] = [], targetDomain = ''): string {
  const lines: string[] = [
    '# ======================================================================',
    '# Apache .htaccess 301 Redirect Rules',
    `# Generated by MigrateShield on ${new Date().toISOString()}`,
    '# ======================================================================',
    '',
    '<IfModule mod_rewrite.c>',
    '  RewriteEngine On',
    '  RewriteBase /',
    ''
  ];

  // Active Synthesized Regex Patterns
  const activePatterns = patterns.filter(p => p.isActive);
  if (activePatterns.length > 0) {
    lines.push('  # --- Synthesized Directory & Regex Rules ---');
    for (const p of activePatterns) {
      lines.push(`  # ${p.name} (Replaces ~${p.affectedCount} static rules)`);
      const tgtPrefix = targetDomain ? `https://${targetDomain}` : '';
      lines.push(`  RewriteRule ${p.sourcePattern} ${tgtPrefix}${p.targetPattern} [R=301,L]`);
    }
    lines.push('');
  }

  lines.push('  # --- Specific Page-to-Page 301 Redirects ---');
  for (const m of mappings) {
    if (m.status === 'GONE_410' || m.statusCode === 410) {
      lines.push(`  RewriteRule ^${m.source.normalizedPath.replace(/^\//, '')}$ - [G,L]`);
    } else if (m.targetUrl && m.targetUrl !== m.source.url) {
      const srcPath = m.source.normalizedPath.replace(/^\//, '');
      const tgtPath = m.target ? m.target.normalizedPath : m.targetUrl;
      const tgtPrefix = targetDomain ? `https://${targetDomain}` : '';
      lines.push(`  RewriteRule ^${srcPath}$ ${tgtPrefix}${tgtPath} [R=301,L]`);
    }
  }

  lines.push('</IfModule>');
  return lines.join('\n');
}

/**
 * Generates Nginx rewrite configuration
 */
export function generateNginx(mappings: UrlMapping[], patterns: SynthesizedPattern[] = [], targetDomain = ''): string {
  const lines: string[] = [
    '# ======================================================================',
    '# Nginx 301 Redirect Rules',
    `# Generated by MigrateShield on ${new Date().toISOString()}`,
    '# ======================================================================',
    ''
  ];

  const activePatterns = patterns.filter(p => p.isActive);
  if (activePatterns.length > 0) {
    lines.push('# --- Regex Pattern Rewrites ---');
    for (const p of activePatterns) {
      lines.push(`# ${p.name}`);
      const tgtPrefix = targetDomain ? `https://${targetDomain}` : '';
      lines.push(`rewrite ${p.sourcePattern} ${tgtPrefix}${p.targetPattern} permanent;`);
    }
    lines.push('');
  }

  lines.push('# --- Individual 301 Rewrites ---');
  for (const m of mappings) {
    if (m.status === 'GONE_410' || m.statusCode === 410) {
      lines.push(`location = ${m.source.normalizedPath} { return 410; }`);
    } else if (m.targetUrl && m.targetUrl !== m.source.url) {
      const tgtPath = m.target ? m.target.normalizedPath : m.targetUrl;
      const tgtPrefix = targetDomain ? `https://${targetDomain}` : '';
      lines.push(`rewrite ^${m.source.normalizedPath}$ ${tgtPrefix}${tgtPath} permanent;`);
    }
  }

  return lines.join('\n');
}

/**
 * Generates Cloudflare Bulk Redirects CSV
 */
export function generateCloudflareCsv(mappings: UrlMapping[], targetDomain = ''): string {
  const rows = mappings
    .filter(m => m.targetUrl && m.targetUrl !== m.source.url)
    .map(m => ({
      source_url: m.source.url,
      target_url: m.target ? m.target.url : (targetDomain ? `https://${targetDomain}${m.targetUrl}` : m.targetUrl),
      status_code: m.statusCode || 301,
      preserve_query_string: 'TRUE',
      subpath_matching: 'FALSE',
      preserve_path_suffix: 'FALSE',
      include_subdomains: 'FALSE'
    }));

  return Papa.unparse(rows);
}

/**
 * Generates Vercel / Netlify _redirects file
 */
export function generateVercelRedirects(mappings: UrlMapping[]): string {
  const lines: string[] = [
    '# Vercel & Netlify _redirects format',
    `# Generated: ${new Date().toISOString()}`,
    ''
  ];

  for (const m of mappings) {
    if (m.status === 'GONE_410' || m.statusCode === 410) {
      lines.push(`${m.source.normalizedPath} /410.html 410!`);
    } else if (m.targetUrl && m.targetUrl !== m.source.url) {
      const tgt = m.target ? m.target.normalizedPath : m.targetUrl;
      lines.push(`${m.source.normalizedPath} ${tgt} 301!`);
    }
  }

  return lines.join('\n');
}

/**
 * Generates Next.js next.config.js redirects snippet
 */
export function generateNextJsConfig(mappings: UrlMapping[]): string {
  const redirects = mappings
    .filter(m => m.targetUrl && m.targetUrl !== m.source.url)
    .map(m => ({
      source: m.source.normalizedPath,
      destination: m.target ? m.target.normalizedPath : m.targetUrl,
      permanent: m.statusCode === 301,
    }));

  return `// Add this to your next.config.js / next.config.mjs
/** @type {import('next').NextConfig} */
const nextConfig = {
  async redirects() {
    return ${JSON.stringify(redirects, null, 2)};
  },
};

module.exports = nextConfig;
`;
}

/**
 * Generates WordPress Redirection Plugin CSV
 */
export function generateWordpressRedirectionCsv(mappings: UrlMapping[]): string {
  const rows = mappings.map(m => ({
    source: m.source.normalizedPath,
    target: m.target ? m.target.normalizedPath : m.targetUrl,
    code: m.statusCode || 301,
    regex: 0,
    match: 'url',
    action: (m.status === 'GONE_410' || m.statusCode === 410) ? 'error' : 'url',
    title: `MigrateShield auto-map (${m.strategy})`
  }));

  return Papa.unparse(rows);
}

/**
 * Generates Comprehensive Full Mapping CSV
 */
export function generateFullMappingCsv(mappings: UrlMapping[]): string {
  const targetCounts = new Map<string, number>();
  for (const m of mappings) {
    if (m.targetUrl && m.status !== 'GONE_410' && m.strategy !== 'UNMAPPED') {
      const url = m.targetUrl.toLowerCase();
      targetCounts.set(url, (targetCounts.get(url) || 0) + 1);
    }
  }

  const rows = mappings.map(m => {
    const getError = (types: string[]) => {
      const disc = m.discrepancies.find(d => types.includes(d.type));
      return disc ? `[${disc.severity}] ${disc.title}` : '';
    };

    return {
      'Source URL': m.source.url,
      'Source Path': m.source.normalizedPath,
      'Source Title': m.source.title,
      'Source Meta Description': m.source.metaDescription,
      'Source H1': m.source.h1,
      'Source Canonical': m.source.canonical,
      'Source Inlinks': m.source.inlinks,
      'Source Status': m.source.statusCode,
      'Source Indexability': m.source.indexability,
      'Recommended Action': (m.status === 'GONE_410' || m.statusCode === 410) ? '410 Gone' : (m.targetUrl && m.targetUrl !== m.source.url ? '301 Redirect' : 'Unmapped'),
      'Target URL': (m.status === 'GONE_410' || m.statusCode === 410) ? 'N/A' : (m.target ? m.target.url : m.targetUrl),
      'Target Path': (m.status === 'GONE_410' || m.statusCode === 410) ? 'N/A' : (m.target ? m.target.normalizedPath : m.targetUrl),
      'Target Title': m.target ? m.target.title : '',
      'Target Meta Description': m.target ? m.target.metaDescription : '',
      'Target H1': m.target ? m.target.h1 : '',
      'Target Canonical': m.target ? m.target.canonical : '',
      'Target Status': m.target ? m.target.statusCode : '',
      'Target Indexability': m.target ? m.target.indexability : '',
      'Is Conflict': (m.targetUrl && m.status !== 'GONE_410' && m.strategy !== 'UNMAPPED' && (targetCounts.get(m.targetUrl.toLowerCase()) || 0) > 1) ? 'TRUE' : 'FALSE',
      'Notes': m.notes || '',
      'Match Confidence (%)': m.confidenceScore,
      'Strategy': m.strategy,
      'Status': m.status,
      'Risk Score (0-100)': m.riskScore,
      'Discrepancies Count': m.discrepancies.length,
      'Error: Target Status': getError(['TARGET_404_OR_500']),
      'Error: Indexability': getError(['NOINDEX_ON_TARGET']),
      'Error: Canonical': getError(['CANONICAL_MISMATCH']),
      'Error: Word Count': getError(['WORD_COUNT_COLLAPSE']),
      'Error: Title': getError(['TITLE_DISCREPANCY']),
      'Error: H1': getError(['H1_MISSING']),
      'Error: Meta Description': getError(['META_DESCRIPTION_DROPPED']),
      'Error: Routing': getError(['SOFT_404_HOMEPAGE_TRAP']),
      'Discrepancies Summary': m.discrepancies.map(d => `[${d.severity}] ${d.title}`).join(' | ')
    };
  });

  return Papa.unparse(rows);
}

/**
 * Generates XML Sitemap for 200 OK target URLs
 */
export function generateSitemap(mappings: UrlMapping[], targetDomain = ''): string {
  const lines: string[] = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
  ];
  
  const includedUrls = new Set<string>();

  for (const m of mappings) {
    if (m.targetUrl && m.status !== 'GONE_410' && m.target && m.target.statusCode === 200) {
      const tgtUrl = targetDomain ? `https://${targetDomain}${m.target.normalizedPath}` : m.targetUrl;
      if (!includedUrls.has(tgtUrl)) {
        includedUrls.add(tgtUrl);
        lines.push('  <url>');
        lines.push(`    <loc>${tgtUrl}</loc>`);
        lines.push(`    <changefreq>weekly</changefreq>`);
        lines.push(`    <priority>0.8</priority>`);
        lines.push('  </url>');
      }
    }
  }

  lines.push('</urlset>');
  return lines.join('\n');
}

/**
 * Master dispatcher for exports
 */
export function exportRedirects(
  format: ExportFormat,
  mappings: UrlMapping[],
  patterns: SynthesizedPattern[] = [],
  targetDomain = '',
  stats: MigrationSummaryStats | null = null,
  projectMetadata: ProjectMetadata | null = null,
  checklistProgress: Record<string, boolean> = {},
  targetEntries: any[] = []
): { content: string | Uint8Array; filename: string; mimeType: string } {
  switch (format) {
    case 'HTACCESS':
      return {
        content: generateHtaccess(mappings, patterns, targetDomain),
        filename: '.htaccess',
        mimeType: 'text/plain'
      };
    case 'NGINX':
      return {
        content: generateNginx(mappings, patterns, targetDomain),
        filename: 'nginx_redirects.conf',
        mimeType: 'text/plain'
      };
    case 'CLOUDFLARE_CSV':
      return {
        content: generateCloudflareCsv(mappings, targetDomain),
        filename: 'cloudflare_bulk_redirects.csv',
        mimeType: 'text/csv'
      };
    case 'VERCEL_REDIRECTS':
      return {
        content: generateVercelRedirects(mappings),
        filename: '_redirects',
        mimeType: 'text/plain'
      };
    case 'NEXTJS_CONFIG':
      return {
        content: generateNextJsConfig(mappings),
        filename: 'next.config.js',
        mimeType: 'application/javascript'
      };
    case 'WORDPRESS_REDIRECTION_CSV':
      return {
        content: generateWordpressRedirectionCsv(mappings),
        filename: 'wordpress_redirection.csv',
        mimeType: 'text/csv'
      };
    case 'FULL_AUDIT_EXCEL':
      return {
        content: generateFullAuditExcel(mappings, stats, projectMetadata, checklistProgress),
        filename: 'migration_playbook_and_audit.xlsx',
        mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
      };
    case 'SITEMAP_XML':
      return {
        // Fallback to mappings-based sitemap if targetEntries is empty or missing
        content: targetEntries.length > 0 
          ? generateXmlSitemap(targetEntries) 
          : generateSitemap(mappings, targetDomain),
        filename: 'sitemap.xml',
        mimeType: 'application/xml'
      };
    case 'FULL_MAPPING_CSV':
    default:
      return {
        content: generateFullMappingCsv(mappings),
        filename: 'migration_mapping_full.csv',
        mimeType: 'text/csv'
      };
  }
}

/**
 * Generates an Excel Workbook with multiple sheets: 
 * Sheet 1: Mappings, Sheet 2: Playbook
 */
export function generateFullAuditExcel(
  mappings: UrlMapping[],
  stats: MigrationSummaryStats | null,
  projectMetadata: ProjectMetadata | null,
  checklistProgress: Record<string, boolean>
): Uint8Array {
  const wb = XLSX.utils.book_new();

  // --- SHEET 1: Redirect Mappings ---
  const targetCounts = new Map<string, number>();
  for (const m of mappings) {
    if (m.targetUrl && m.status !== 'GONE_410' && m.strategy !== 'UNMAPPED') {
      const url = m.targetUrl.toLowerCase();
      targetCounts.set(url, (targetCounts.get(url) || 0) + 1);
    }
  }

  const mappingRows = mappings.map(m => {
    const getError = (types: string[]) => {
      const disc = m.discrepancies.find(d => types.includes(d.type));
      return disc ? `[${disc.severity}] ${disc.title}` : '';
    };

    return {
      'Source URL': m.source.url,
      'Source Path': m.source.normalizedPath,
      'Source Title': m.source.title,
      'Source Meta Description': m.source.metaDescription,
      'Source H1': m.source.h1,
      'Source Canonical': m.source.canonical,
      'Source Inlinks': m.source.inlinks,
      'Source Status': m.source.statusCode,
      'Source Indexability': m.source.indexability,
      'Recommended Action': (m.status === 'GONE_410' || m.statusCode === 410) ? '410 Gone' : (m.targetUrl && m.targetUrl !== m.source.url ? '301 Redirect' : 'Unmapped'),
      'Target URL': (m.status === 'GONE_410' || m.statusCode === 410) ? 'N/A' : (m.target ? m.target.url : m.targetUrl),
      'Target Path': (m.status === 'GONE_410' || m.statusCode === 410) ? 'N/A' : (m.target ? m.target.normalizedPath : m.targetUrl),
      'Target Title': m.target ? m.target.title : '',
      'Target Meta Description': m.target ? m.target.metaDescription : '',
      'Target H1': m.target ? m.target.h1 : '',
      'Target Canonical': m.target ? m.target.canonical : '',
      'Target Status': m.target ? m.target.statusCode : '',
      'Target Indexability': m.target ? m.target.indexability : '',
      'Is Conflict': (m.targetUrl && m.status !== 'GONE_410' && m.strategy !== 'UNMAPPED' && (targetCounts.get(m.targetUrl.toLowerCase()) || 0) > 1) ? 'TRUE' : 'FALSE',
      'Notes': m.notes || '',
      'Match Confidence (%)': m.confidenceScore,
      'Strategy': m.strategy,
      'Status': m.status,
      'Risk Score (0-100)': m.riskScore,
      'Discrepancies Count': m.discrepancies.length,
      'Error: Target Status': getError(['TARGET_404_OR_500']),
      'Error: Indexability': getError(['NOINDEX_ON_TARGET']),
      'Error: Canonical': getError(['CANONICAL_MISMATCH']),
      'Error: Word Count': getError(['WORD_COUNT_COLLAPSE']),
      'Error: Title': getError(['TITLE_DISCREPANCY']),
      'Error: H1': getError(['H1_MISSING']),
      'Error: Meta Description': getError(['META_DESCRIPTION_DROPPED']),
      'Error: Routing': getError(['HUB_TRAP_SOFT_404', 'SOFT_404_HOMEPAGE_TRAP']),
      'Discrepancies Summary': m.discrepancies.map(d => `[${d.severity}] ${d.title}`).join(' | ')
    };
  });
  
  const wsMappings = XLSX.utils.json_to_sheet(mappingRows);
  XLSX.utils.book_append_sheet(wb, wsMappings, 'Mapping & Audit');

  // --- SHEET 2: Playbook Data ---
  const playbookRows: any[] = [];
  
  if (projectMetadata) {
    playbookRows.push(
      { Phase: 'Project Meta', Category: 'Info', Task: 'Project Name', Status: '', Details: projectMetadata.projectName },
      { Phase: 'Project Meta', Category: 'Info', Task: 'Client Name', Status: '', Details: projectMetadata.clientName },
      { Phase: 'Project Meta', Category: 'Info', Task: 'Migration Date', Status: '', Details: projectMetadata.targetDate },
      { Phase: 'Project Meta', Category: 'Info', Task: 'CMS / Platform', Status: '', Details: projectMetadata.platform },
      { Phase: 'Project Meta', Category: 'Integrations', Task: 'Google Search Console', Status: projectMetadata.hasGSC ? 'Connected' : 'Pending', Details: '' },
      { Phase: 'Project Meta', Category: 'Integrations', Task: 'Google Analytics 4', Status: projectMetadata.hasGA4 ? 'Connected' : 'Pending', Details: '' },
      { Phase: 'Project Meta', Category: 'Integrations', Task: 'SEMrush / Ahrefs', Status: projectMetadata.hasSEMrush ? 'Connected' : 'Pending', Details: '' }
    );
  }

  // Combine old + new checklists
  for (const checklist of Object.values(MIGRATION_CHECKLISTS)) {
    for (const phase of checklist.phases) {
      for (const item of phase.items) {
        playbookRows.push({
          Phase: phase.title,
          Category: checklist.title,
          Task: item.label,
          Status: checklistProgress[item.id] ? "Done" : "Pending",
          Details: ""
        });
      }
    }
  }

  const wsPlaybook = XLSX.utils.json_to_sheet(playbookRows);
  XLSX.utils.book_append_sheet(wb, wsPlaybook, 'Migration Playbook');

  return XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
}

/**
 * Exports a selected subset of discrepancy items to a CSV file.
 */
export function exportDiscrepanciesToCsv(
  items: Array<{
    type: string;
    severity: string;
    title: string;
    description: string;
    sourceUrl: string;
    sourceValue: string | number;
    targetUrl: string;
    targetValue: string | number;
  }>
): { content: string; filename: string; mimeType: string } {
  const rows = items.map(item => ({
    'Issue Type': item.type,
    'Severity': item.severity,
    'Title': item.title,
    'Description': item.description,
    'Source URL (Old)': item.sourceUrl,
    'Source Value': item.sourceValue,
    'Target URL (New)': item.targetUrl,
    'Target Value': item.targetValue
  }));

  return {
    content: Papa.unparse(rows),
    filename: `seo_discrepancies_export_${new Date().toISOString().split('T')[0]}.csv`,
    mimeType: 'text/csv'
  };
}
